CREATE TABLE "userData" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name_of_unit_holder" varchar,
	"email_id_of_unit_holder" varchar[],
	"mobile_number_of_unit_holder" varchar[],
	"contact_person_unit_holder" varchar[],
	"link_pan__unit_holder" varchar,
	"link_gst_certificate_unit_holder" varchar,
	"existing_building" varchar,
	"existing_unit_number" varchar,
	"existing_floor" varchar,
	"new_building_unit_number" varchar,
	"new_building_floor_number" varchar,
	"area_in_existing_building" varchar,
	"ninety_percent_addi_area" varchar,
	"area_total" varchar,
	"area_in_new_building" varchar,
	"car_paring_floor" varchar,
	"car_parking_number" varchar,
	"link_back_side_number_plate" varchar,
	"name_of_bank_pledge" varchar,
	"address_of_bank_pledge" varchar,
	"date_of_noc_by_awcl_pledge" varchar,
	"type_of_loan_pledge" varchar,
	"link_noc_by_company_pledge" varchar,
	"link_sanction_letter_pledge" varchar,
	"account_name_unit_holder" varchar,
	"bank_name_unit_holder" varchar,
	"address_unit_holder" varchar,
	"account_number_unit_holder" varchar,
	"ifsc_unit_holder" varchar,
	"link_cancelled_cheque_unit_holder" varchar,
	"name_of_lessee_lessee" varchar,
	"date_of_leave_and_licence_document_lessee" varchar,
	"validity_of_lease_and_license_document_lessee" varchar,
	"lessee_nature_of_business" varchar,
	"link_of_lessee_agreement" varchar,
	"name_of_depository_participant_demat" varchar,
	"dp_id_demat" varchar,
	"demat_client_id" varchar,
	"link_holding_attachment_demat" varchar,
	"physical_share_certificate_number" varchar,
	"folio_number_physical_share" varchar,
	"distinctive_number_physical_share" varchar,
	"link_of_share_certificate" varchar,
	"shareHolderData" jsonb[],
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
